publishdir = "docs"
static = "/static"
builddrafts = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
# Replace this with your website URL
baseurl = "https://hes.pzhao.org/"
canonifyurls = true
theme = "hugo-academic-group"
title = "HES-XJTLU"
math = true
copyright = "&copy; Department of Health and Environmental Sciences, XJTLU"
[outputs]
  home = ["HTML", "RSS", "JSON"]
[taxonomies]
category = "categories"
tag = "tags"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[params]
  description = "Website of Department of Health and Environmental Sciences, XJTLU"
  author = "Peng Zhao"
  email = "someone@xjtlu.edu.cn"
  address = "Chongwenlu 8, Suzhou Industrial Park, 215123 Suzhou, Jiangsu Province, China"

  slogan = "HES"
  slogan_text = "Health and Environmental Sciences"

#  [[params.slogan_columns]]
#    title = "Environmental Pollution"
#    text = "- Soil nutrients and pollution – interactions & bioavailability  \n- Air pollution – aerosol processes – air quality – human health  \n- Soils to plants – nutrition/heavy metals – human health  \n- Pollutants across interfaces – soil/water/air/biota/humans"
#    link = "/mission"
#    link_text = "Read more"
#    weight = 1

#  [[params.slogan_columns]]
#    title = "Ecology"
#    text =  "- Biodiversity – mechanisms - human influences  \n- Landscape changes – urbanization – rural farming  \n- Community ecology – species interactions – trophic dynamics"
#    link = "/about"
#    link_text = "Meet the team"
#    weight = 2

#  [[params.slogan_columns]]
#    title = "Public Health"
#    text = "- Epidemiology  \n - Biostatistics"
#    link = "/approach"
#    link_text = "Read more"
#    weight = 3

  [[params.slogan_columns]]
    title = "Our"
    text = "- Undergraduates [link](/post/undergraduates/)  \n- Postgraduates [link](/post/postgraduates/)  \n- Academic Staff [link](/member)  \n- Support Team [link](/post/support_team)  \n- Alumni [link](/post/alumni)"
    weight = 1

  [[params.slogan_columns]]
    title = "Work"
    text = "- Research [link](/project)  \n- Publications [link](/publication)  \n- Teaching [link](/post/module)  \n- Lab [link](https://heslab.pzhao.org/)"
    weight = 2
    
  [[params.slogan_columns]]
    title = "Matters"
    text = "- News [link](/post)  \n- Events [link](/post/events)  \n- Admissions [link](/post/admissions)  \n- About [link](/about)  \n- Contact [link](/#contact)"
    weight = 3

  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 6
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 6
    title = "News"
    subtitle = ""
    str_all = "More news"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Research"
    subtitle = ""
    count = 6
    str_all = "More Research"
  
  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.vacancies]
    title = "Vacancies"
    subtitle = ""
    count = 3
    str_all = "More Vacancies"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "/#top"
      weight = 10

  [[menu.main]]
      name = "Research"
      url = "/#projects"
      weight = 20

  [[menu.main]]
      name = "Publications"
      url = "/#publications"
      weight = 30

  [[menu.main]]
      name = "Teaching"
      url = "/post/module"
      weight = 40
      
  [[menu.main]]
      name = "Staff"
      url = "/#members"
      weight = 50

#  [[menu.main]]
#      name = "Students"
#      url = "/post/students"
#      weight = 60
      
#  [[menu.main]]
#      name = "Alumni"
#      url = "/post/alumni"
#      weight = 70

  [[menu.main]]
      name = "News"
      url = "/#posts"
      weight = 80

#  [[menu.main]]
#      name = "Lab"
#      url = "https://heslab.pzhao.org/"
#      weight = 90

#  [[menu.main]]
#      name = "Contact"
#      url = "/#contact"
#      weight = 110
      
  [[menu.main]]
      name = "About"
      url = "/about"
      weight = 120
      
  [[menu.main]]
      name = "中文"
      url = "/zh"
      weight = 130

# 中文界面

[languages.zh.params]
  description = "Website of Department of Health and Environmental Sciences, XJTLU"
  author = "Peng Zhao"
  email = "someone@xjtlu.edu.cn"
  address = "中国江苏省苏州市工业园区崇文路 8 号新兴科学楼，邮编 215123"

  slogan = "HES"
  slogan_text = "健康与环境科学系"


  [[languages.zh.params.slogan_columns]]
    title = "我们的"
    text = "- 本科生 [link](/zh/post/undergraduates/)  \n- 博士生 [link](/zh/post/postgraduates/)  \n- 教师 [link](/zh/member)  \n- 支持团队 [link](/zh/post/support_team)  \n- 校友 [link](/zh/post/alumni)"
    weight = 1

  [[languages.zh.params.slogan_columns]]
    title = "工作"
    text = "- 科研 [link](/zh/project)  \n- 著作 [link](/zh/publication) \n- 教学 [link](/zh/post/module)  \n- 实验室 [link](https://heslab.pzhao.org/)"
    weight = 2
    
  [[languages.zh.params.slogan_columns]]
    title = "和其他"
    text = "- 新闻 [link](/zh/post)  \n- 活动 [link](/zh/post/events)  \n- 关于 [link](/zh/about)  \n- 招生 [link](/zh/post/admissions)  \n- 联系我们 [link](/zh/#contact)"
    weight = 3

  # Selected Publications section.
  [languages.zh.params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [languages.zh.params.publications]
    count = 6
    detailed_list = false
    title = "著作"
    subtitle = "论文，书籍，专利"
    str_all = "更多著作"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [languages.zh.params.posts]
    count = 6
    title = "新闻"
    subtitle = ""
    str_all = "更多新闻"
    str_read_more = "阅读全文"
    url = "/zh/post"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [languages.zh.params.projects]
    title = "科研"
    subtitle = ""
    count = 6
    str_all = "更多科研"
  
  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [languages.zh.params.vacancies]
    title = "Vacancies"
    subtitle = ""
    count = 3
    str_all = "More Vacancies"

  # Contact section.
  [languages.zh.params.contact]
    enable = true
    title = "联系我们"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  [[languages.zh.menu.main]]
      name = "首页"
      url = "/zh/#top"
      weight = 10

  [[languages.zh.menu.main]]
      name = "科研"
      url = "/zh/#projects"
      weight = 20

  [[languages.zh.menu.main]]
      name = "著作"
      url = "/zh/#publications"
      weight = 30

  [[languages.zh.menu.main]]
      name = "教学"
      url = "/zh/post/module"
      weight = 40
      
  [[languages.zh.menu.main]]
      name = "师资"
      url = "/zh/#members"
      weight = 50

#  [[languages.zh.menu.main]]
#      name = "Students"
#      url = "/post/students"
#      weight = 60
      
#  [[languages.zh.menu.main]]
#      name = "Alumni"
#      url = "/post/alumni"
#      weight = 70

  [[languages.zh.menu.main]]
      name = "新闻"
      url = "/zh/#posts"
      weight = 80

#  [[languages.zh.menu.main]]
#      name = "Lab"
#      url = "https://heslab.pzhao.org/"
#      weight = 90

#  [[languages.zh.menu.main]]
#      name = "Contact"
#      url = "/#contact"
#      weight = 110
      
  [[languages.zh.menu.main]]
      name = "简介"
      url = "/zh/about"
      weight = 120

  [[languages.zh.menu.main]]
      name = "English"
      url = "/"
      weight = 130

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"

[languages.zh]
  languageCode = "zh-cn"