publishdir = "docs"
static = "/static"
builddrafts = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
# Replace this with your website URL
baseurl = "https://hes.pzhao.org/"
canonifyurls = true
theme = "hugo-academic-group"
title = "HES-XJTLU"
math = true
copyright = "&copy; Department of Health and Environmental Sciences, XJTLU"

[taxonomies]
category = "categories"
tag = "tags"


[params]
  description = "Website of Department of Health and Environmental Sciences, XJTLU"
  author = "Peng Zhao"
  email = "someone@xjtlu.edu.cn"
  address = "Chongwenlu 8, Suzhou Industrial Park, 215123 Suzhou, Jiangsu Province, China"

  slogan = "HES"
  slogan_text = "Health and Environmental Sciences"

#  [[params.slogan_columns]]
#    title = "Environmental Pollution"
#    text = "- Soil nutrients and pollution – interactions & bioavailability  \n- Air pollution – aerosol processes – air quality – human health  \n- Soils to plants – nutrition/heavy metals – human health  \n- Pollutants across interfaces – soil/water/air/biota/humans"
#    link = "/mission"
#    link_text = "Read more"
#    weight = 1

#  [[params.slogan_columns]]
#    title = "Ecology"
#    text =  "- Biodiversity – mechanisms - human influences  \n- Landscape changes – urbanization – rural farming  \n- Community ecology – species interactions – trophic dynamics"
#    link = "/about"
#    link_text = "Meet the team"
#    weight = 2

#  [[params.slogan_columns]]
#    title = "Public Health"
#    text = "- Epidemiology  \n - Biostatistics"
#    link = "/approach"
#    link_text = "Read more"
#    weight = 3

  [[params.slogan_columns]]
    title = "People"
    text = "- Academic Staff [link](/#members)  \n- Support Team [link](/post/support_team)  \n- PhD Students [link](/post/students/)  \n- Alumni [link](/post/alumni)"
    weight = 1

  [[params.slogan_columns]]
    title = "Work"
    text = "- Research [link](/#projects)  \n- Publications [link](/#publications) \n- Projects [link](/post/projects)  \n- Modules [link](/post/module)"
    weight = 2
    
  [[params.slogan_columns]]
    title = "Log"
    text = "- News [link](/post)  \n- Lab [link](https://heslab.pzhao.org/)  \n- About [link](/about)  \n- Contact [link](/#contact)"
    weight = 3

  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 5
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 6
    title = "News"
    subtitle = ""
    str_all = "More news"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Research"
    subtitle = ""
    count = 7
    str_all = "More Research"
  
  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.vacancies]
    title = "Vacancies"
    subtitle = ""
    count = 3
    str_all = "More Vacancies"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "/#top"
      weight = 10

  [[menu.main]]
      name = "Research"
      url = "/#projects"
      weight = 20

  [[menu.main]]
      name = "Publications"
      url = "/#publications"
      weight = 30

  [[menu.main]]
      name = "Modules"
      url = "/post/module"
      weight = 40
      
  [[menu.main]]
      name = "Staff"
      url = "/#members"
      weight = 50

  [[menu.main]]
      name = "Students"
      url = "/post/students"
      weight = 60
      
  [[menu.main]]
      name = "Alumni"
      url = "/post/alumni"
      weight = 70

  [[menu.main]]
      name = "News"
      url = "/#posts"
      weight = 80

  [[menu.main]]
      name = "Lab"
      url = "https://heslab.pzhao.org/"
      weight = 90

  [[menu.main]]
      name = "Contact"
      url = "/#contact"
      weight = 110
      
  [[menu.main]]
      name = "About"
      url = "/about"
      weight = 120
