---
title: 关于
slug: about
---

<iframe src="../../html/HES_emphasis_areas/Knops.Johannes_HES_emphasis_areas.html" width="800" height="450px"></iframe>

[全屏](../../html/HES_emphasis_areas/Knops.Johannes_HES_emphasis_areas.html)

健康与环境科学系结合独特的科学方法来理解和解决当今社会所面临的一些最关键的挑战。

我们的专业为学生提供了成功的职业生涯所需要的理论和实践基础，以改善公共健康和环境。学生将获得在自然科学、社会科学，医学以及人文学科方面的坚实基础，并形成关于改善公共健康以及全球化环境问题背后复杂过程的完整视野。

我们将研究直接引入课堂，并为学生提供理论与最新的公共健康和环境科学知识相结合的学习体验。

## 公共健康

人类健康永远是全世界共同关注的议题。目前，人类健康面临多种多样的挑战——快速增长的老龄化人口、城市化、气候变化、新发现的疾病、可持续发展、环境恶化、人为的或自然灾害、医疗体系改革等等。

公共健康是一个跨学科领域，旨在提升和维持人类的健康、安全和福利，防范与管理疾病、残障和痛苦，我系科研活动和学术团队正是在不断探索这一议题。

## 环境科学

环境科学已逐渐成长为多学科交叉的学术领域，整合了物理和生态科学知识，用科学方法研究人类活动对自然资源的影响。环境问题在中国政治、经济发展日程上的重要性日益提升，因此，我国的环境科学家肩负重任，探寻着针对中国以及其他地区迫切的环境问题的解决方案，例如气候变化问题、水污染、空气污染、土壤污染、土地使用变更（土壤沙漠化、食品安全）、水资源问题（洪灾、水资源短缺）、能源供给问题，以及生物多样性的消失等。环境问题和挑战层出不穷，接踵而至。

我系课程教学教授学生扎实的物理和生态科学知识，培养调查诸多环境问题的技能和寻求问题管控及解决方法的能力。我系致力于为毕业生提供就业或继续学业所需的重要技能。

### 联系我们

```{r, echo=FALSE}
xjtlu::get_map(longitude = 120.7405, latitude = 31.2686, latitude_view = 31.2686 + 0.003)
```

- 电邮: someone@xjtlu.edu.cn
- 地址: 中国江苏省苏州市工业园区崇文路 8 号新兴科学楼，邮编 215123

<video id="example_video_1" class="video-js vjs-default-skin vjs-fluid" controls="" preload="none" poster="https://play.xjtlu.edu.cn/d33b4a8ce3984172ba48e102ceaaf8c2/snapshots/7da9e6b5c2a8486ba0c765ccb1e2a465-00005.jpg">
<source src="https://play.xjtlu.edu.cn/sv/54f8b7fc-17195d88845/54f8b7fc-17195d88845.mp4" type="video/mp4">	
</video>
